AWSTemplateFormatVersion: '2010-09-09'
Description: >
  HA Web Platform - VPC, ALB, ASG, EC2, CloudWatch (minimal, secure, reproducible)
  # This template provisions a highly available web platform across two AZs with
  # Application Load Balancer, Auto Scaling Group, and CloudWatch alarm.
  # All resources are for lab/testing purposes only and should be destroyed after use.
  # Security: No SSH open to the world. Only HTTP via ALB. EC2 only accessible from ALB SG.

Parameters:
  VpcCidr:
    Type: String
    Default: 10.0.0.0/16
    Description: CIDR block for the VPC
  PublicSubnet1Cidr:
    Type: String
    Default: 10.0.1.0/24
    Description: CIDR block for public subnet 1 (AZ1)
  PublicSubnet2Cidr:
    Type: String
    Default: 10.0.2.0/24
    Description: CIDR block for public subnet 2 (AZ2)
  InstanceType:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t3.micro
      - t3.small
    Description: EC2 instance type for ASG (use free tier for lab)
  MinSize:
    Type: Number
    Default: 2
    Description: Minimum number of EC2 instances in ASG
  MaxSize:
    Type: Number
    Default: 2
    Description: Maximum number of EC2 instances in ASG
  AmiId:
    Type: AWS::EC2::Image::Id
    Description: AMI ID for EC2 instances (default: latest Amazon Linux 2)
    Default: ami-0c02fb55956c7d316
  AlbHealthCheckPath:
    Type: String
    Default: /
    Description: Health check path for ALB

Resources:
  HaWebVpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCidr
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: HaWebVpc

  HaWebPublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref HaWebVpc
      CidrBlock: !Ref PublicSubnet1Cidr
      AvailabilityZone: !Select [0, !GetAZs '']
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: HaWebPublicSubnet1

  HaWebPublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref HaWebVpc
      CidrBlock: !Ref PublicSubnet2Cidr
      AvailabilityZone: !Select [1, !GetAZs '']
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: HaWebPublicSubnet2

  HaWebInternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: HaWebInternetGateway

  HaWebVpcGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref HaWebVpc
      InternetGatewayId: !Ref HaWebInternetGateway

  HaWebPublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref HaWebVpc
      Tags:
        - Key: Name
          Value: HaWebPublicRouteTable

  HaWebPublicRoute:
    Type: AWS::EC2::Route
    DependsOn: HaWebVpcGatewayAttachment
    Properties:
      RouteTableId: !Ref HaWebPublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref HaWebInternetGateway

  HaWebSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref HaWebPublicSubnet1
      RouteTableId: !Ref HaWebPublicRouteTable

  HaWebSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref HaWebPublicSubnet2
      RouteTableId: !Ref HaWebPublicRouteTable

  HaWebAlbSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP from anywhere (only for ALB)
      VpcId: !Ref HaWebVpc
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0  # HTTP only, no SSH, safe for public web access
      SecurityGroupEgress:
        - IpProtocol: -1
          FromPort: 0
          ToPort: 0
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: HaWebAlbSecurityGroup

  HaWebEc2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP only from ALB SG (no public access)
      VpcId: !Ref HaWebVpc
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          SourceSecurityGroupId: !Ref HaWebAlbSecurityGroup
      SecurityGroupEgress:
        - IpProtocol: -1
          FromPort: 0
          ToPort: 0
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: HaWebEc2SecurityGroup

  HaWebApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: HaWebApplicationLoadBalancer
      Scheme: internet-facing
      Subnets:
        - !Ref HaWebPublicSubnet1
        - !Ref HaWebPublicSubnet2
      SecurityGroups:
        - !Ref HaWebAlbSecurityGroup
      Type: application
      IpAddressType: ipv4
      Tags:
        - Key: Name
          Value: HaWebApplicationLoadBalancer

  HaWebTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: HaWebTargetGroup
      Port: 80
      Protocol: HTTP
      VpcId: !Ref HaWebVpc
      HealthCheckPath: !Ref AlbHealthCheckPath
      TargetType: instance
      Matcher:
        HttpCode: 200
      Tags:
        - Key: Name
          Value: HaWebTargetGroup

  HaWebAlbListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref HaWebApplicationLoadBalancer
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref HaWebTargetGroup

  HaWebLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: HaWebLaunchTemplate
      LaunchTemplateData:
        ImageId: !Ref AmiId
        InstanceType: !Ref InstanceType
        SecurityGroupIds:
          - !Ref HaWebEc2SecurityGroup
        UserData:
          Fn::Base64: !Sub |
            #!/bin/bash
            # Simple web server for lab/demo: returns instance ID and AZ for ALB health check and demo
            # Uses AWS metadata IP 169.254.169.254 (safe, not a public or personal IP)
            echo "<h1>Instance ID: $(curl -s http://169.254.169.254/latest/meta-data/instance-id)</h1><h2>AZ: $(curl -s http://169.254.169.254/latest/meta-data/placement/availability-zone)</h2>" > /var/www/html/index.html
            yum install -y httpd
            systemctl enable httpd
            systemctl start httpd
            cp /var/www/html/index.html /var/www/html/health.html
        TagSpecifications:
          - ResourceType: instance
            Tags:
              - Key: Name
                Value: HaWebEc2Instance

  HaWebAutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      VPCZoneIdentifier:
        - !Ref HaWebPublicSubnet1
        - !Ref HaWebPublicSubnet2
      LaunchTemplate:
        LaunchTemplateId: !Ref HaWebLaunchTemplate
        Version: !GetAtt HaWebLaunchTemplate.LatestVersionNumber
      MinSize: !Ref MinSize
      MaxSize: !Ref MaxSize
      TargetGroupARNs:
        - !Ref HaWebTargetGroup
      HealthCheckType: EC2
      HealthCheckGracePeriod: 60
      Tags:
        - Key: Name
          Value: HaWebAutoScalingGroup
          PropagateAtLaunch: true

  HaWebCpuAlarmHigh:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: 'Alarm if average CPU > 70% for 5 minutes (scaling demo)'
      Namespace: AWS/EC2
      MetricName: CPUUtilization
      Dimensions:
        - Name: AutoScalingGroupName
          Value: !Ref HaWebAutoScalingGroup
      Statistic: Average
      Period: 300
      EvaluationPeriods: 1
      Threshold: 70
      ComparisonOperator: GreaterThanThreshold
      AlarmActions: [] # No scaling policy attached, just for demo/visibility
      OKActions: []
      InsufficientDataActions: []

Outputs:
  HaWebAlbDnsName:
    Description: DNS name of the Application Load Balancer
    Value: !GetAtt HaWebApplicationLoadBalancer.DNSName
  HaWebVpcId:
    Description: VPC ID
    Value: !Ref HaWebVpc
  HaWebPublicSubnet1Id:
    Description: Public Subnet 1 ID
    Value: !Ref HaWebPublicSubnet1
  HaWebPublicSubnet2Id:
    Description: Public Subnet 2 ID
    Value: !Ref HaWebPublicSubnet2
